### ISSUE TITLE
Error Forbidden upon local registration 

### ISSUE THREAD

**Issue by shadoobie** [pilwon/ultimate-seed#3]
Hello,

I'm wondering if I'm doing this wrong.  I've setup ultimate-seed such that I have all of the dependencies and modules.  I've got redis running and on the default port.  The site comes up correctly for the most part.  In some cases there is no login or register button (chromebook and chrome on vista)

When I register using the standard passport I get the following error.  It does appear that my user can log in.  However on the 1st login, they also get a similar error.
# 

Error: Forbidden
    at Object.exports.error (/home/shadoobie/workspaces/website/ultimate-seed/node_modules/express/node_modules/connect/lib/utils.js:60:13)
    at /home/shadoobie/workspaces/website/ultimate-seed/node_modules/express/node_modules/connect/lib/middleware/csrf.js:54:41
    at module.exports (/home/shadoobie/workspaces/website/ultimate-seed/node_modules/ultimate/lib/server/controller/csrf.js:10:17)
    at callbacks (/home/shadoobie/workspaces/website/ultimate-seed/node_modules/express/lib/router/index.js:161:37)
    at module.exports (/home/shadoobie/workspaces/website/ultimate-seed/node_modules/ultimate/lib/server/controller/ensureLoggedOut.js:11:3)
    at callbacks (/home/shadoobie/workspaces/website/ultimate-seed/node_modules/express/lib/router/index.js:161:37)
    at param (/home/shadoobie/workspaces/website/ultimate-seed/node_modules/express/lib/router/index.js:135:11)
    at pass (/home/shadoobie/workspaces/website/ultimate-seed/node_modules/express/lib/router/index.js:142:5)
    at Router._dispatch (/home/shadoobie/workspaces/website/ultimate-seed/node_modules/express/lib/router/index.js:170:5)
    at Object.router (/home/shadoobie/workspaces/website/ultimate-seed/node_modules/express/lib/router/index.js:33:10)
    at next (/home/shadoobie/workspaces/website/ultimate-seed/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at next (/home/shadoobie/workspaces/website/ultimate-seed/node_modules/express/node_modules/connect/lib/proto.js:192:9)
    at Object.static (/home/shadoobie/workspaces/website/ultimate-seed/node_modules/express/node_modules/connect/lib/middleware/static.js:55:61)
    at next (/home/shadoobie/workspaces/website/ultimate-seed/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at next (/home/shadoobie/workspaces/website/ultimate-seed/node_modules/express/node_modules/connect/lib/proto.js:165:78)
    at Object.handle (/home/shadoobie/workspaces/website/ultimate-seed/server/app.js:115:5)
    at next (/home/shadoobie/workspaces/website/ultimate-seed/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at Object.handle (/home/shadoobie/workspaces/website/ultimate-seed/node_modules/ultimate/lib/server/middleware/hidePoweredByHeader.js:16:5)
    at Context.next (/home/shadoobie/workspaces/website/ultimate-seed/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at Context.actions.pass (/home/shadoobie/workspaces/website/ultimate-seed/node_modules/passport/lib/passport/context/http/actions.js:77:8)
    at SessionStrategy.authenticate (/home/shadoobie/workspaces/website/ultimate-seed/node_modules/passport/lib/passport/strategies/session.js:52:10)
    at attempt (/home/shadoobie/workspaces/website/ultimate-seed/node_modules/passport/lib/passport/middleware/authenticate.js:243:16)
    at Passport.authenticate (/home/shadoobie/workspaces/website/ultimate-seed/node_modules/passport/lib/passport/middleware/authenticate.js:244:7)
    at next (/home/shadoobie/workspaces/website/ultimate-seed/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at Passport.initialize (/home/shadoobie/workspaces/website/ultimate-seed/node_modules/passport/lib/passport/middleware/initialize.js:69:5)
    at next (/home/shadoobie/workspaces/website/ultimate-seed/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at Object.handle (/home/shadoobie/workspaces/website/ultimate-seed/node_modules/ultimate/lib/server/middleware/methodOverride.js:27:5)
    at next (/home/shadoobie/workspaces/website/ultimate-seed/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at Object.methodOverride [as handle](/home/shadoobie/workspaces/website/ultimate-seed/node_modules/express/node_modules/connect/lib/middleware/methodOverride.js:37:5)
    at next (/home/shadoobie/workspaces/website/ultimate-seed/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at next (/home/shadoobie/workspaces/website/ultimate-seed/node_modules/express/node_modules/connect/lib/middleware/session.js:313:9)
    at /home/shadoobie/workspaces/website/ultimate-seed/node_modules/express/node_modules/connect/lib/middleware/session.js:337:9
    at /home/shadoobie/workspaces/website/ultimate-seed/node_modules/connect-mongo/lib/connect-mongo.js:192:17
    at /home/shadoobie/workspaces/website/ultimate-seed/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/collection.js:1010:5
    at Cursor.nextObject (/home/shadoobie/workspaces/website/ultimate-seed/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/cursor.js:653:5)
    at commandHandler (/home/shadoobie/workspaces/website/ultimate-seed/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/cursor.js:635:14)
    at null.<anonymous> (/home/shadoobie/workspaces/website/ultimate-seed/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/db.js:1709:18)
    at g (events.js:175:14)
    at EventEmitter.emit (events.js:106:17)
    at Server.Base._callHandler (/home/shadoobie/workspaces/website/ultimate-seed/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/base.js:130:25)
    at /home/shadoobie/workspaces/website/ultimate-seed/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:522:20
    at MongoReply.parseBody (/home/shadoobie/workspaces/website/ultimate-seed/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:132:5)
    at null.<anonymous> (/home/shadoobie/workspaces/website/ultimate-seed/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:481:22)
    at EventEmitter.emit (events.js:95:17)
    at null.<anonymous> (/home/shadoobie/workspaces/website/ultimate-seed/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:190:13)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (/home/shadoobie/workspaces/website/ultimate-seed/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:382:22)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:699:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:382:10)
    at emitReadable (_stream_readable.js:377:5)
    at readableAddChunk (_stream_readable.js:142:7)
    at Socket.Readable.push (_stream_readable.js:112:10)
#     at TCP.onread (net.js:496:21)

**Comment by pilwon** [comment]
@shadoobie Thanks for reporting the issue. There was a bug with generation of CSRF token for not-yet-POSTed requests.
